spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teacher-appointment?serverTimezone=GMT&useUnicode=true&characterEncoding=GBK
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: stx12345
#    url: jdbc:mysql://wxdypsql.mysql.rds.aliyuncs.com:3306/petrochinadb?serverTimezone=GMT&useUnicode=true&characterEncoding=GBK
#    driver-class-name: com.mysql.jdbc.Driver
#    username: petrochinadb
#    password: TrmPetro@2018
  freemarker:
    template-loader-path: classpath:/templates/
    charset: UTF-8
    cache: false
    suffix: .ftl
    content-type: text/html
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 80